import React from "react";
import { Form, DatePicker, Button, Space, Input } from "antd";
import { Typography } from "antd";
import { useState } from "react";
const { Text } = Typography;

const SummariesSearchForm = () => {

  const [fromDate, setfromDate] = useState("")
  const [toDate, settoDate] = useState("")
  const [generatedBy, setGeneratedBy] = useState("")

  const handleFromDate = (date, dateString) => {
    setfromDate(dateString)
  }

  const handleToDate = (date, dateString) => {
    settoDate(dateString)
  }

  const handleGeneratedBy = (e) => {
    setGeneratedBy(e.target.value)
  }

  const handleSearch = (event) => {
    event.preventDefault()
    console.log("Generated By: " + generatedBy);
    console.log("From Date: " + fromDate);
    console.log("To Date: " + toDate);
  }

  const handleReset = () => {
    setGeneratedBy("")
    setfromDate("")
    settoDate("");
  }

  return (
    <Form className="search-form">
      <div className="form-item">
        <label>
          <Text strong>From Date</Text>
        </label>
        <DatePicker onChange={handleFromDate} />
      </div>

      <div className="form-item">
        <label className="form-label">
          <Text strong>To Date</Text>
        </label>
        <DatePicker onChange={handleToDate} />
      </div>

      <div className="form-item">
        <label className="form-label">
          <Text strong>Generated By</Text>
        </label>
        <Input value={generatedBy} onChange={handleGeneratedBy} />
      </div>

      <div className="form-item-special">
        <Space>
          <Button htmlType="submit" onClick={handleReset}>
            Reset
          </Button>
          <Button type="primary" onClick={handleSearch}>
            Search
          </Button>
        </Space>
      </div>
    </Form>
  );
};

export default SummariesSearchForm;
