export const columns = [
    {
        title: "S/N",
        dataIndex: "sn",
    },
    {
        title: "Name",
        dataIndex: "name",
    },
    {
        title: "Path",
        dataIndex: "path",
    },
    {
        title: "Date Issued",
        dataIndex: "dateissued",
    },
    {
        title: "Generated By",
        dataIndex: "generatedby",
    },
];

export const data = [
    {
        key: 1,
        sn: 1,
        name: "Jan.csv",
        path: "server/graphs/jan.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Sherlock Holmes",
    },
    {
        key: 2,
        sn: 2,
        name: "Feb.csv",
        path: "server/graphs/feb.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "James Bond",
    },
    {
        key: 3,
        sn: 3,
        name: "March.csv",
        path: "server/graphs/march.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "John Doe",
    },
    {
        key: 4,
        sn: 4,
        name: "April.csv",
        path: "server/graphs/april.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Jane Doe",
    },
    {
        key: 5,
        sn: 5,
        name: "May.csv",
        path: "server/graphs/may.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Harry Maguire",
    },
    {
        key: 6,
        sn: 6,
        name: "June.csv",
        path: "server/graphs/march.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Paul Pogba",
    },

    {
        key: 7,
        sn: 7,
        name: "July.csv",
        path: "server/graphs/july.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Cristiano Ronaldo",
    },
    {
        key: 8,
        sn: 8,
        name: "Aug.csv",
        path: "server/graphs/aug.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Juan Mata",
    },
    {
        key: 9,
        sn: 9,
        name: "Sept.csv",
        path: "server/graphs/sept.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Anthony Martial",
    },
    {
        key: 10,
        sn: 10,
        name: "Oct.csv",
        path: "server/graphs/oct.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Marcus Rashford",
    },
    {
        key: 11,
        sn: 11,
        name: "Nov.csv",
        path: "server/graphs/nov.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Mason Greenwood",
    },
    {
        key: 12,
        sn: 12,
        name: "Dec.csv",
        path: "server/graphs/dec.pdf",
        dateissued: `${new Date().getTime()}`,
        generatedby: "Chris Smalling",
    },
];

